//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HelpDesk
    {

        [Required(ErrorMessage = "Enter the UserName")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Enter the Password")]
        public string Password { get; set; }
        public string Roletype { get; set; }
        public int User_Id { get; set; }

        [Required(ErrorMessage = "Enter the Valid Email")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
    }
}
