//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class TicketTable
    {
        public int Ticket_Id { get; set; }
        public string CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string Subject { get; set; }
        public int Status { get; set; }
        public System.DateTime DateTime { get; set; } = DateTime.Now;
        public int User_Id { get; set; }
        public string Image_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<int> Dep_ID { get; set; }
    }
}
